### ISSUE TITLE
Certificat expira 23/12/2020

### ISSUE THREAD

**Issue by jcastany** [ConsorciAOC/Applet-de-signatura#1]
L'applet fa referència a un certificat del CONSORCI ADMINISTRACIO OBERTA ELECTRONICA DE CATALUNYA, amb serial number: 1551918562....  que caduca el 23/12/2020. Està previst publicar-ne una actualització que li allargui la vida més enllà? Moltes gràcies.

**Comment by albciff** [comment]
Hola @jcastany,

En principi tal i com s'indica: https://github.com/ConsorciAOC/Applet-de-signatura

El EOL del applet és de Maig de 2017, és una tecnologia en desús ja no suportada per la majoria de navegadors ens les seves versions actuals. A priori no està previst resignar amb aquests jars amb nous certificats, però arribat el cas i amb la necessitat justificada entenc que es podria fer. Personalment ja no em dedico a aquest projecte, ho hauries de demanar al CAOC a través del següent enllaç de la web de suport: https://www.aoc.cat/portal-suport/necessiteu-mes-ajuda/

Gràcies,

**Comment by albciff** [comment]
Hola @jcastany 

Finalment hem davant de peticions fetes per diversos clients, hem optat per ressignar els components. Han estat ressignats i actualitzats.
